version: '3.9'
services:
  db:
    image: mysql:5.7
    volumes:
      - mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
  banking_app:
    build: .
    environment:
      - DB_HOST=${DB_HOST}
    command: bash -c "bundle exec rails db:create db:migrate db:seed && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/banking_app
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  mysql: